//
//  TermsView.swift
//  boilerplate
//
//  Terms & Conditions Screen
//  Created by Ankur on 1/12/26.
//

import SwiftUI

struct TermsView: View {
    @Environment(\.dismiss) private var dismiss
    
    var body: some View {
        NavigationStack {
            ZStack {
                // Background
                DesignSystem.Colors.backgroundPrimary
                    .ignoresSafeArea()
                
                ScrollView {
                    VStack(alignment: .leading, spacing: DesignSystem.Spacing.lg) {
                        // Header
                        VStack(alignment: .leading, spacing: DesignSystem.Spacing.sm) {
                            Text("Terms & Conditions")
                                .font(.system(size: 28, weight: .bold))
                                .foregroundColor(DesignSystem.Colors.primaryOrange)
                            
                            Text("Last updated: January 2026")
                                .font(.system(size: 14))
                                .foregroundColor(DesignSystem.Colors.textSecondary)
                        }
                        .padding(.top, DesignSystem.Spacing.lg)
                        
                        Divider()
                            .background(DesignSystem.Colors.border)
                        
                        // Content
                        VStack(alignment: .leading, spacing: DesignSystem.Spacing.lg) {
                            termsSection(
                                title: "1. Acceptance of Terms",
                                content: "By accessing and using Posterized, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to these terms, please do not use our service."
                            )
                            
                            termsSection(
                                title: "2. Use of Service",
                                content: "Posterized is an entertainment app that generates AI-powered sports roasts. You agree to use this service for lawful purposes only. You must not use the app to:\n\n• Harass, abuse, or harm others\n• Post or transmit illegal content\n• Impersonate any person or entity\n• Interfere with the service's operation"
                            )
                            
                            termsSection(
                                title: "3. User Content",
                                content: "You retain all rights to the content you input into Posterized. By using our service, you grant us a license to process your inputs to generate AI responses. Generated content is for entertainment purposes only and should not be taken as factual statements."
                            )
                            
                            termsSection(
                                title: "4. AI-Generated Content",
                                content: "All roasts are generated by artificial intelligence. Posterized does not guarantee the accuracy, quality, or appropriateness of AI-generated content. Users are responsible for how they use and share generated content."
                            )
                            
                            termsSection(
                                title: "5. Subscriptions and Payments",
                                content: "Premium subscriptions are billed through the Apple App Store. Subscriptions automatically renew unless auto-renew is turned off at least 24 hours before the end of the current period. Refunds are subject to Apple's refund policy."
                            )
                            
                            termsSection(
                                title: "6. Intellectual Property",
                                content: "The Posterized app, including its design, features, and functionality, is owned by us and protected by copyright, trademark, and other intellectual property laws."
                            )
                            
                            termsSection(
                                title: "7. Disclaimer of Warranties",
                                content: "Posterized is provided \"as is\" without warranties of any kind, either express or implied. We do not warrant that the service will be uninterrupted, timely, secure, or error-free."
                            )
                            
                            termsSection(
                                title: "8. Limitation of Liability",
                                content: "To the maximum extent permitted by law, Posterized shall not be liable for any indirect, incidental, special, consequential, or punitive damages resulting from your use of the service."
                            )
                            
                            termsSection(
                                title: "9. Changes to Terms",
                                content: "We reserve the right to modify these terms at any time. We will notify users of any material changes. Your continued use of the service after changes constitutes acceptance of the new terms."
                            )
                            
                            termsSection(
                                title: "10. Contact Information",
                                content: "If you have any questions about these Terms & Conditions, please contact us at:\n\nsupport@posterized.app"
                            )
                        }
                    }
                    .padding(.horizontal, DesignSystem.Spacing.lg)
                    .padding(.bottom, DesignSystem.Spacing.xxl)
                }
            }
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .navigationBarTrailing) {
                    Button(action: { dismiss() }) {
                        Image(systemName: "xmark.circle.fill")
                            .font(.title3)
                            .foregroundColor(DesignSystem.Colors.textSecondary)
                    }
                }
            }
        }
    }
    
    private func termsSection(title: String, content: String) -> some View {
        VStack(alignment: .leading, spacing: DesignSystem.Spacing.sm) {
            Text(title)
                .font(.system(size: 18, weight: .semibold))
                .foregroundColor(DesignSystem.Colors.textPrimary)
            
            Text(content)
                .font(.system(size: 15))
                .foregroundColor(DesignSystem.Colors.textSecondary)
                .lineSpacing(4)
        }
    }
}

#Preview {
    TermsView()
}
